<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    ...
  </PropertyGroup>

  <ItemGroup>
    ...
  </ItemGroup>

  <!-- ADD THIS BLOCK HERE -->
  <ItemGroup>
    <Reference Include="GrapeCity.Enterprise.Identity.SecurityProvider">
      <HintPath>C:\Program Files\Wyn Enterprise\Server\GrapeCity.Enterprise.Identity.SecurityProvider.dll</HintPath>
    </Reference>
    <Reference Include="GrapeCity.Enterprise.Identity.ExternalIdentityProvider">
      <HintPath>C:\Program Files\Wyn Enterprise\Server\GrapeCity.Enterprise.Identity.ExternalIdentityProvider.dll</HintPath>
    </Reference>
    <Reference Include="GrapeCity.Enterprise.Identity.ExternalIdentityProvider.Configuration">
      <HintPath>C:\Program Files\Wyn Enterprise\Server\GrapeCity.Enterprise.Identity.ExternalIdentityProvider.Configuration.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
