<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>CustomSecProvider.RA</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup Condition="$([MSBuild]::IsOSPlatform('Windows')) and Exists('C:\Program Files\Wyn Enterprise\Server\GrapeCity.Enterprise.Identity.SecurityProvider.dll')">
    <Reference Include="GrapeCity.Enterprise.Identity.SecurityProvider">
      <HintPath>C:\Program Files\Wyn Enterprise\Server\GrapeCity.Enterprise.Identity.SecurityProvider.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="GrapeCity.Enterprise.Identity.ExternalIdentityProvider">
      <HintPath>C:\Program Files\Wyn Enterprise\Server\GrapeCity.Enterprise.Identity.ExternalIdentityProvider.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="GrapeCity.Enterprise.Identity.ExternalIdentityProvider.Configuration">
      <HintPath>C:\Program Files\Wyn Enterprise\Server\GrapeCity.Enterprise.Identity.ExternalIdentityProvider.Configuration.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
